[package]
name = "logviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
ratatui = "0.29"
crossterm = "0.28"
regex = "1"
fancy-regex = "0.14"
notify = "7"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
